### ISSUE TITLE
specが走るごとにランダムに変更される文字列

### ISSUE THREAD

**Issue by shin1ohno** [r7kamura/autodoc#10]
いまいち解決策が思いつかないんだけど、Fakerとかを使ってて、specごとに変わってしまう文字列に影響されてドキュメントが更新されるのが面倒。

変更内容をチェックしてリポジトリにコミットしなければいいだけといえばそれまでなんだけど。

**Comment by okuramasafumi** [comment]
判定ロジックを完璧なものにするのは極めて難しいと思うのですが、ほぼ間違いなく毎回変わるものに関してはデフォルトで、そうでないものに関してはオプションで指定できるようにする（指定の方法はいいのが思いつきませんが…）というのはどうでしょうか。
ほぼ間違いなく毎回変わるもの、というのは、各モデルのIDと外部キー、それにタイムスタンプ（`created_at`と`updated_at`）があるかと思います。ひとまずこれだけを除外するだけでもだいぶノイズは減るのではないでしょうか。
