### ISSUE TITLE
How to specify Required/Optional for params?

### ISSUE THREAD

**Issue by lazywei** [r7kamura/autodoc#27]
Hi,

I noticed that in https://github.com/r7kamura/autodoc/blob/master/spec/dummy/doc/recipes.md, there are something like
![image](https://cloud.githubusercontent.com/assets/2840571/7224554/6935a0d2-e766-11e4-85dc-4195938f2217.png)

But in
https://github.com/r7kamura/autodoc/blob/master/spec/requests/recipes_spec.rb
I didn't find any specific syntax to specify this. I'm wondering how to specify the required/optional or other params description?

thanks

**Comment by r7kamura** [comment]
@lazywei Sorry, that is un-documented feature of [weak_parameters](https://github.com/r7kamura/weak_parameters) integration. I just updated README about that.  https://github.com/r7kamura/autodoc/commit/45e81d54d67b414d3fd4b1e3286bd429e5cc858b
Thanks for issueing :pray:

**Comment by lazywei** [comment]
Thanks for elaborating.

However, I'm thinking if it would be better to have this feature inside autodoc instead of coupling with weak_parameters? It would be perfect if I can specify the required/optional inside the spec files instead of in the controllers files.

Thanks.
