### ISSUE TITLE
Auto docs generator 

### ISSUE THREAD

**Issue by SamuraiT** [r7kamura/autodoc#31]
#10 と少し被りますが、自動でドキュメントを生成する設定の追加を検討しています。

idea
------
基本はgit commitの変更履歴（時間）を見ます。
e.g
- `spec/spam_spec.rb`が変更のcommitを行い、かつ`doc/spam.md`がgit logにないならば`spam.md`生成。
- `doc/spam.md`がgit logにあるが、コミットされた時間が
 - `time('doc/spam.md') < time('spec/spam_spec.rb') `ならば、`spam.md`を生成。
 - それ以外（`time('doc/spam.md') >= time('spec/spam_spec.rb')`）ならば生成しない。

`Autodoc.configuration.automatic_doc_generation = true`なら`AUTODOC=1 bundle rspec spec/`を実行するときに実行されるようにしたいと考えています。

いかがでしょうか？

**Comment by SamuraiT** [comment]
あれ、spec/spam_spec.rbがcommitされた時点で、生成するのと変わらない

**Comment by r7kamura** [comment]
Gitが利用できる環境であることや、Gitで管理されたレポジトリであるということに依存した機能を入れるのはあまり良くないんじゃないかと思っています。

**Comment by SamuraiT** [comment]
先ほど他の方とも相談し、同じ結論に至りました。フィードバックありがとうございます！

**Comment by r7kamura** [comment]
:pray:

**Comment by r7kamura** [comment]
テストファイルの変更だけがドキュメントの内容に影響するという訳ではないので、実装や依存しているライブラリのバージョン、テストを実行する時間帯や順序などが変わればドキュメントの内容も当然変わる可能性があって、テストファイルの変更時刻についてだけ関心を持つのはあんまり安心できないなあとも思ってました

**Comment by SamuraiT** [comment]
確かにそのとおりです．ありがとうございます！
