### ISSUE TITLE
Encoding::CompatibilityError: incompatible character encodings: ASCII-8BIT and UTF-8

### ISSUE THREAD

**Issue by ponoda** [r7kamura/autodoc#43]
### 環境

```sh
$ ruby -v
ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin15]

$ bundle exec rails -v
Rails 5.1.3

$ grep autodoc Gemfile.lock
Gemfile.lock:    autodoc (0.6.1)
Gemfile.lock:  autodoc
```

### 現象

```sh
$ AUTODOC=1 bundle exec rspec spec/requests/api/hoge_spec.rb
... 

An error occurred in an `after(:suite)` hook.
Failure/Error: Unable to find (erb) to read failed line

Encoding::CompatibilityError:
  incompatible character encodings: ASCII-8BIT and UTF-8
# (erb):16:in `concat'
# (erb):16:in `render'
```

### 原因

`lib/autodoc/templates/document.md.erb` で以下の値の encoding が `US-ASCII` でした。
- `method`
- `request_query`
- `request_body_section`
- `response.status`

**Comment by ponoda** [comment]
手元ではとりあえず以下の独自templatesを指定して、
問題の値に `.to_s.force_encoding('UTF-8')` とすることで回避しています。

---

in `spec/spec_helper.rb`
```rb
Autodoc.configuration.template = File.read(Rails.root.join('spec/support/autodoc/templates/document.md.erb'))
```

> $ diff vendor/bundle/ruby/2.4.0/gems/autodoc-0.6.1/lib/autodoc/templates/document.md.erb spec/support/autodoc/templates/document.md.erb
https://gist.github.com/ponoda/0151caeb7270b704a525f96e90781af7

**Comment by r7kamura** [comment]
おー、ありがとうございます。これまで見たことなかったけど、最近の変更でエラーが出るようになったとかですかね？

**Comment by ponoda** [comment]
厳密にいつからと切り分けできていないんですが、過去には実行できていたものが最近修正したらこのエラーが発生した、ということがありました。今日、新規に作成したspecでも発生しました。

**Comment by r7kamura** [comment]
https://github.com/r7kamura/autodoc/pull/42 で入れた変更のせいかもしれない? @hiroki-uchida

**Comment by hiroki-uchida** [comment]
@r7kamura 

> #42 で入れた変更のせいかもしれない? @hiroki-uchida

> Gemfile.lock:    autodoc (0.6.1)

https://github.com/r7kamura/autodoc/pull/42 は6.2からなので違うかも?

@ponoda 

https://github.com/r7kamura/autodoc/issues/41 こちらと同じ、もしくは似た問題のように見えます。

0.6.2で`request_query`のみ対応しているので(https://github.com/r7kamura/autodoc/pull/42)、 バージョンアップで一部解決するかもしれません。

ただ、`method` `request_body_section` `response.status`もとなると新たに対応が必要そうです。

もし可能でしたら0.6.2での動作状況を貼っていただけますか。

**Comment by ponoda** [comment]
@r7kamura @hiroki-uchida
v0.6.2 に上げたところエラーが発生しなくなりました。 
#41 と同件で修正済みということですね。お騒がせしました 🙏
