### ISSUE TITLE
配布されているパッケージに"broken symlink"が含まれている

### ISSUE THREAD

**Issue by ReoKuriyama** [r7kamura/autodoc#44]
https://github.com/rubygems/rubygems/pull/2516
こちらのPRにより、`spec/dummy/spec`にはられているシンボリックリンクがおかしくなっていたのが修正されたので、versionを変えて再リリースをお願いしたいです。

**Comment by r7kamura** [comment]
v0.7.1 をリリースして対応しました、ありがとうございます 👍
